namespace Domain.Enuns.Pessoas
{
    public static class BancoHelpPessoaLista
    {
        public class Banco
        {
            public int Codigo { get; set; }
            public string? Nome { get; set; }
        }

        static List<Banco> Bancos = new List<Banco>()
                    {
                        new Banco(){ Codigo = 654, Nome = "A.J. RENNER S.A." },
                        new Banco(){ Codigo = 246, Nome = "ABC-BRASIL S.A." },
                        new Banco(){ Codigo = 213, Nome = "ARBI S.A." },
                        new Banco(){ Codigo = 19, Nome = "AZTECA DO BRASIL S.A." },
                        new Banco(){ Codigo = 25, Nome = "BANCO ALFA" },
                        new Banco(){ Codigo = 241, Nome = "Banco Classico S.A" },
                        new Banco(){ Codigo = 83, Nome = "BANCO DA CHINA BRASIL S.A." },
                        new Banco(){ Codigo = 300, Nome = "BANCO DE LA NACION ARGENTINA" },
                        new Banco(){ Codigo = 495, Nome = "BANCO DE LA PROVINCIA DE BUENOS AIRES" },
                        new Banco(){ Codigo = 494, Nome = "BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY" },
                        new Banco(){ Codigo = 1, Nome = "BANCO DO BRASIL" },
                        new Banco(){ Codigo = 37, Nome = "BANCO DO ESTADO DO PARÁ S.A" },
                        new Banco(){ Codigo = 456, Nome = "BANCO TOKYO MITSUBISH UFJ BRASIL S.A" },
                        new Banco(){ Codigo = 370, Nome = "BANCO WESTLB DO BRASIL" },
                        new Banco(){ Codigo = 756, Nome = "BANCOOB" },
                        new Banco(){ Codigo = 47, Nome = "BANESE" },
                        new Banco(){ Codigo = 33, Nome = "BANESPA" },
                        new Banco(){ Codigo = 21, Nome = "BANESTES" },
                        new Banco(){ Codigo = 719, Nome = "BANIF-BANCO INTERNACIONAL DO FUNCHAL (BRASIL) S.A" },
                        new Banco(){ Codigo = 755, Nome = "BANK OF AMERICA MERRILL LYNCH BANCO MULTIPLO S.A." },
                        new Banco(){ Codigo = 41, Nome = "BANRISUL" },
                        new Banco(){ Codigo = 740, Nome = "BARCLAYS S.A." },
                        new Banco(){ Codigo = 3, Nome = "BASA" },
                        new Banco(){ Codigo = 107, Nome = "BBM S.A" },
                        new Banco(){ Codigo = 81, Nome = "BBN BANCO BRASILEIRO DE NEGOCIOS S.A" },
                        new Banco(){ Codigo = 250, Nome = "BCV - BANCO DE CREDITO E VAREJO S.A" },
                        new Banco(){ Codigo = 36, Nome = "BEM" },
                        new Banco(){ Codigo = 122, Nome = "BERJ S.A" },
                        new Banco(){ Codigo = 78, Nome = "BES INVESTIMENTO DO BRASIL SA - BANCO DE INVESTIM." },
                        new Banco(){ Codigo = 739, Nome = "BGN S.A." },
                        new Banco(){ Codigo = 320, Nome = "BIC BANCO" },
                        new Banco(){ Codigo = 96, Nome = "BM&F DE SERV. DE LIQUIDACAO E CUSTODIA S.A" },
                        new Banco(){ Codigo = 394, Nome = "BMC S.A." },
                        new Banco(){ Codigo = 318, Nome = "BMG S.A." },
                        new Banco(){ Codigo = 4, Nome = "BNB" },
                        new Banco(){ Codigo = 752, Nome = "BNP PARIBAS BRASIL S.A" },
                        new Banco(){ Codigo = 17, Nome = "BNY MELLON S.A." },
                        new Banco(){ Codigo = 248, Nome = "BOA VISTA INTERATLANTICO S.A" },
                        new Banco(){ Codigo = 218, Nome = "BONSUCESSO S.A." },
                        new Banco(){ Codigo = 69, Nome = "BPN BRASIL BANCO MULTIPLO S.A" },
                        new Banco(){ Codigo = 65, Nome = "BRACCE S.A." },
                        new Banco(){ Codigo = 237, Nome = "BRADESCO" },
                        new Banco(){ Codigo = 225, Nome = "BRASCAN S.A." },
                        new Banco(){ Codigo = 125, Nome = "BRASIL PLURAL S.A. BANCO MULTIPLO" },
                        new Banco(){ Codigo = 70, Nome = "BRB" },
                        new Banco(){ Codigo = 92, Nome = "BRICKELL S A CREDITO, FINANCIAMENTO E INVESTIMENTO" },
                        new Banco(){ Codigo = 208, Nome = "BTG PACTUAL S.A." },
                        new Banco(){ Codigo = 263, Nome = "CACIQUE S.A." },
                        new Banco(){ Codigo = 104, Nome = "CAIXA ECON. FEDERAL" },
                        new Banco(){ Codigo = 473, Nome = "CAIXA GERAL - BRASIL S.A." },
                        new Banco(){ Codigo = 412, Nome = "CAPITAL S.A." },
                        new Banco(){ Codigo = 40, Nome = "CARGILL S.A" },
                        new Banco(){ Codigo = 112, Nome = "CC UNICRED BRASIL CENTRAL" },
                        new Banco(){ Codigo = 84, Nome = "CC UNIPRIME NORTE DO PARANA" },
                        new Banco(){ Codigo = 114, Nome = "CECOOPES-CENTRAL DAS COOP DE ECON E CRED MUTUO DO" },
                        new Banco(){ Codigo = 85, Nome = "CECREDI" },
                        new Banco(){ Codigo = 266, Nome = "CEDULA S.A." },
                        new Banco(){ Codigo = 233, Nome = "CIFRA S.A." },
                        new Banco(){ Codigo = 745, Nome = "CITIBANK" },
                        new Banco(){ Codigo = 477, Nome = "Citibank N.A." },
                        new Banco(){ Codigo = 90, Nome = "COOPERATIVA CENTRAL DE CREDITO DO ESTADO DE SP" },
                        new Banco(){ Codigo = 97, Nome = "COOPERATIVA CENTRAL DE CREDITO NOROESTE BRASILEIRO" },
                        new Banco(){ Codigo = 89, Nome = "COOPERATIVA DE CREDITO RURAL DA REGIAO DA MOGIANA" },
                        new Banco(){ Codigo = 75, Nome = "CR2 S.A" },
                        new Banco(){ Codigo = 98, Nome = "CREDIALIANCA COOPERATIVA DE CREDITO RURAL" },
                        new Banco(){ Codigo = 222, Nome = "CREDIT AGRICOLE BRASIL S.A." },
                        new Banco(){ Codigo = 505, Nome = "CREDIT SUISSE (BRASIL) S.A." },
                        new Banco(){ Codigo = 707, Nome = "DAYCOVAL" },
                        new Banco(){ Codigo = 487, Nome = "DEUTSCHE BANK S. A. - BANCO ALEMAO" },
                        new Banco(){ Codigo = 214, Nome = "DIBENS S.A." },
                        new Banco(){ Codigo = 265, Nome = "FATOR S.A." },
                        new Banco(){ Codigo = 224, Nome = "FIBRA" },
                        new Banco(){ Codigo = 626, Nome = "FICSA S.A." },
                        new Banco(){ Codigo = 121, Nome = "GERADOR S.A." },
                        new Banco(){ Codigo = 612, Nome = "GUANABARA S.A." },
                        new Banco(){ Codigo = 62, Nome = "HIPERCARD BANCO MULTIPLO S.A" },
                        new Banco(){ Codigo = 399, Nome = "HSBC" },
                        new Banco(){ Codigo = 63, Nome = "IBI" },
                        new Banco(){ Codigo = 604, Nome = "INDUSTRIAL DO BRASIL S. A." },
                        new Banco(){ Codigo = 653, Nome = "INDUSVAL S.A." },
                        new Banco(){ Codigo = 492, Nome = "ING BANK N.V." },
                        new Banco(){ Codigo = 630, Nome = "INTERCAP S.A." },
                        new Banco(){ Codigo = 77, Nome = "INTERMEDIUM S.A." },
                        new Banco(){ Codigo = 249, Nome = "Investcred Unibanco" },
                        new Banco(){ Codigo = 341, Nome = "ITAÚ" },
                        new Banco(){ Codigo = 652, Nome = "ITAU HOLDING FINANCEIRA S.A" },
                        new Banco(){ Codigo = 184, Nome = "Itaú-BBA" },
                        new Banco(){ Codigo = 74, Nome = "J. SAFRA S.A." },
                        new Banco(){ Codigo = 376, Nome = "J.P. MORGAN S.A." },
                        new Banco(){ Codigo = 217, Nome = "JOHN DEERE S.A." },
                        new Banco(){ Codigo = 488, Nome = "JPMORGAN CHASE BANK" },
                        new Banco(){ Codigo = 76, Nome = "KDB DO BRASIL S.A" },
                        new Banco(){ Codigo = 757, Nome = "KEB DO BRASIL S.A." },
                        new Banco(){ Codigo = 600, Nome = "Luso Brasileiro" },
                        new Banco(){ Codigo = 243, Nome = "MAXIMA S.A." },
                        new Banco(){ Codigo = 389, Nome = "MERCANTIL DO BRASIL" },
                        new Banco(){ Codigo = 746, Nome = "MODAL S.A." },
                        new Banco(){ Codigo = 66, Nome = "MORGAN STANLEY DEAN WITTER S.A" },
                        new Banco(){ Codigo = 14, Nome = "NATIXIS BRASIL S.A. - BANCO MòLTIPLO" },
                        new Banco(){ Codigo = 753, Nome = "NBC BANK BRASIL S.A.- BANCO MULTIPLO" },
                        new Banco(){ Codigo = 45, Nome = "OPPORTUNITY S.A." },
                        new Banco(){ Codigo = 79, Nome = "ORIGINAL DO AGRONEGOCIO S.A." },
                        new Banco(){ Codigo = 212, Nome = "ORIGINAL S.A." },
                        new Banco(){ Codigo = 623, Nome = "PANAMERICANO" },
                        new Banco(){ Codigo = 254, Nome = "PARANA BANCO S.A." },
                        new Banco(){ Codigo = 611, Nome = "PAULISTA" },
                        new Banco(){ Codigo = 613, Nome = "PECUNIA S.A." },
                        new Banco(){ Codigo = 94, Nome = "PETRA S.A." },
                        new Banco(){ Codigo = 643, Nome = "PINE S.A." },
                        new Banco(){ Codigo = 735, Nome = "POTTENCIAL S.A." },
                        new Banco(){ Codigo = 747, Nome = "RABOBANK INTERNATIONAL BRASIL S.A." },
                        new Banco(){ Codigo = 88, Nome = "RANDON S.A." },
                        new Banco(){ Codigo = 633, Nome = "RENDIMENTO S.A." },
                        new Banco(){ Codigo = 741, Nome = "RIBEIRÃO PRETO" },
                        new Banco(){ Codigo = 120, Nome = "RODOBENS S.A" },
                        new Banco(){ Codigo = 453, Nome = "RURAL" },
                        new Banco(){ Codigo = 72, Nome = "RURAL MAIS S.A" },
                        new Banco(){ Codigo = 422, Nome = "SAFRA" },
                        new Banco(){ Codigo = 751, Nome = "SCOTIABANK BRASIL S.A BANCO MULTIPLO" },
                        new Banco(){ Codigo = 743, Nome = "SEMEAR S.A." },
                        new Banco(){ Codigo = 748, Nome = "SICREDI" },
                        new Banco(){ Codigo = 749, Nome = "SIMPLES S.A." },
                        new Banco(){ Codigo = 366, Nome = "SOCIETE GENERALE BRASIL S.A" },
                        new Banco(){ Codigo = 637, Nome = "SOFISA S.A." },
                        new Banco(){ Codigo = 464, Nome = "SUMITOMO MITSUI BRASILEIRO S.A." },
                        new Banco(){ Codigo = 82, Nome = "TOPAZIO S.A." },
                        new Banco(){ Codigo = 634, Nome = "Triangulo" },
                        new Banco(){ Codigo = 230, Nome = "UNICARD BANCO MULTIPLO S.A" },
                        new Banco(){ Codigo = 91, Nome = "UNICRED CENTRAL RS - CENTRAL DE COOP ECON CRED MUT" },
                        new Banco(){ Codigo = 87, Nome = "UNICRED CENTRAL SANTA CATARINA" },
                        new Banco(){ Codigo = 99, Nome = "UNIPRIME CENTRAL - CENTRAL INT DE COOP DE CRED LTD" },
                        new Banco(){ Codigo = 655, Nome = "VOTORANTIM" },
                        new Banco(){ Codigo = 610, Nome = "VR S.A." },
                        new Banco(){ Codigo = 119, Nome = "WESTERN UNION DO BRASIL S.A." },
                        new Banco(){ Codigo = 124, Nome = "WOORI BANK DO BRASIL S.A." }
                    };

        public static Banco GetBancoByCodigoBanco(int codigo)
        {
            return Bancos.Where(banco => banco.Codigo == codigo).SingleOrDefault();
        }
    }
}
